"""
These tests cover the Contact page.
"""


# ---------------------------------------------------------------
# Imports
# ---------------------------------------------------------------

from pages.contact import RodneyCodesContact


# ---------------------------------------------------------------
# Tests
# ---------------------------------------------------------------

def test_contact_us(browser):
    contact_page = RodneyCodesContact(browser)
    NAME = "Rodney Test Automation"
    EMAIL = "rodneygauna@gmail.com"
    PHONE = "7605870052"
    MESSAGE = "This email was generated by a Selenium PyTest"

    # Given the Contact Us page is displayed
    contact_page.load()

    # When the user adds their contact information
    contact_page.contact(NAME, EMAIL, PHONE, MESSAGE)
    submit_button = contact_page.browser.find_element_by_id("submit")
    submit_button.click()

    # Then the submission is successful
    success_banner = contact_page.browser.find_element_by_class_name(
        "alert-success")
    assert success_banner
